### ISSUE TITLE
Compilation issues with MSVC

### ISSUE THREAD

**Issue by lluchs** [imneme/pcg-cpp#11] opened 2016-04-22 08:57 UTC
See this commit: https://github.com/openclonk/openclonk/commit/02c8dc970ab2814352a72e65dfdc5e06536ed562

Basically, the `always_inline` attribute and the endianness detection don't work there.

**Comment by jkhoogland** [comment] 2016-07-27 21:39
Hi Melissa,
thanks for creating this very nice library. Very elegant.

Is there any change this will be addressed in a new release anytime in the near future ?
I noticed that there has been no commit since the beginning of last year.

I would really like to use the generators on win, osx and linux.

Thanks
Jiri

**Comment by 0joshuaolson1** [comment] 2017-06-13 22:16
Or use it now, shunning MSVC.

**Comment by JubilantJerry** [comment] 2017-06-14 03:08
I too have the same problem. I could at least make the files compile without warnings if I:

* Remove the ``always_inline`` attribute on pcg_random.hpp:1206 (Compiler error)
* Change (v & -v) to (v & (~v + 1)) on pcg_uint128.hpp:161 (I get a warning otherwise)
* Define PCG_LITTLE_ENDIAN=1 during compilation

I have not tested correctness after these changes.

**Comment by 0joshuaolson1** [comment] 2017-06-14 12:25
The emulated 128 bit math is very buggy. I happen to be working on a replacement.

**Comment by CynicalApe** [comment] 2017-07-23 12:53
I've managed to make it work with the Visual C++ compiler on my fork but now it doesn't work with GNU compilers. https://github.com/CynicalApe/pcg-cpp

**Comment by kareldonk** [comment] 2017-08-16 22:01
for the (v & -v) warning/error when compiling with MSVC disable it as follows adding one line before you include the pcg random header.

#pragma warning(disable:4146)
#include <pcg_random.hpp>

Regarding the always inline attribute issue on MSVC, change that line to:

__forceinline result_type operator()()

**Comment by vedranmiletic** [comment] 2019-11-24 16:18
This is still the case with MSVC 2019. Any chance of this being fixed in the official release as proposed in [openclonk/openclonk@02c8dc9](https://github.com/openclonk/openclonk/commit/02c8dc970ab2814352a72e65dfdc5e06536ed562)?

**Comment by vedranmiletic** [comment] 2020-02-06 10:05
@imneme would you accept a PR with this patch?

**Comment by imneme** [comment] 2021-03-30 22:41
I think this old MSVC issue was fixed some time ago. Reopen if not.

**Closed by imneme** 2021-03-30 22:41 UTC

**Comment by sellicott** [comment] 2021-04-17 01:59
I can confirm that this is still an issue

**Comment by imneme** [comment] 2021-04-17 03:18
Which version of MSVC? The latest version on Windows 10 seems to be fine for me.

**Comment by sellicott** [comment] 2021-04-17 13:34
I am using Visual Studio Community 2019. This was my fault, I was using an older version of the library for my Windows build, not the github version. Once I updated, it built correctly.
Thanks!
