### ISSUE TITLE
Typedef Bug

### ISSUE THREAD

**Issue by ThelDoctor** [imneme/pcg-cpp#13] opened 2017-01-09 12:37 UTC
[pcg_random](pcg-cpp/include/pcg_random.hpp) seems to have a bug at lines 1703-1704, namely,
these lines
```
typedef pcg_engines::ext_setseq_xsh_rr_64_32<6,16,true>     pcg32_k2;
typedef pcg_engines::ext_oneseq_xsh_rs_64_32<6,32,true>     pcg32_k2_fast;
```
should read
```
typedef pcg_engines::ext_setseq_xsh_rr_64_32<1,16,true>     pcg32_k2;
typedef pcg_engines::ext_oneseq_xsh_rs_64_32<1,32,true>     pcg32_k2_fast;
``` 
If the intention was to create a typedef for a 2-dimensionally equidistributed generator.

**Comment by 0joshuaolson1** [comment] 2017-06-03 00:35
Duplicate of #9

**Comment by imneme** [comment] 2017-06-03 01:33
Resolved.

**Closed by imneme** 2017-06-03 01:33 UTC
